version: '3.1'

services:
  postgres:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - obscuria-pg:/var/lib/postgresql/data

volumes:
  obscuria-pg:
